spring:
  application:
    name: ms-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/PorcelJhoan/MicroServicios
          default-label: main
          search-paths: config-data
server:
  port: 8888
