# REGISTRAR CLIENTE PUERTO CUSTOMER
POST http://localhost:9091/actuator/refresh

###
# REGISTRAR CLIENTE PUERTO CUSTOMER
POST http://192.168.1.7:9092/v1/api/customer/save
Content-Type: application/json

{
  "name":"Jhoan ",
  "lasName": "Porcel",
  "email": "jhoan.porcel6@gmail.com"
}

### OBTENER TODOS LOS CLIENTES PUERTO CUSTOMER

GET http://localhost:9091/v1/api/customer/test
Accept: application/json

### OBTENER INFORMACIÓN DE UN CLIENTE PUERTO CUSTOMER

GET http://localhost:9091/v1/api/customer?idcustomer=1
Accept: application/json

### REGISTRAR CLIENTE PUERTO GATEWAY

POST http://localhost:8283/ms-customer/v1/api/customer/save
Content-Type: application/json

{
  "name":"Jhoan ",
  "lasName": "Porcel",
  "email": "jhoan.porcel6@gmail.com"
}

### OBTENER TODOS LOS CLIENTES PUERTO GATEWAY

GET http://localhost:8283/ms-customer/v1/api/customer/test
Accept: application/json

### OBTENER INFORMACIÓN DE UN CLIENTE PUERTO GATEWAY

GET http://localhost:8283/ms-customer/v1/api/customer?idcustomer=1
Accept: application/json

###

