server:
  port: 8283
spring:
  zipkin:
    base-url: http://localhost:9411
  application:
    name: ms-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    enabled: true
  instance:
    prefer-ip-address: true