version: "2.4"
services:
  ms-discovery:
    image: ms-discovery:0.0.1
    mem_limit: 120m
    ports:
    - "8761:8761"

  ms-customer:
    image: ms-customer:0.0.1
    mem_limit: 200m
    ports:
    - "9091:9091"
    environment:
      - "EUREKA_URI=http://192.168.1.2:8761/eureka"
    depends_on:
      ms-discovery:
        condition: service_started
