### NOTIFICACION CORREO PUERTO NOTIFICATION
POST http://localhost:8150/v1/api/notification/correo
Content-Type: application/json

{
  "notificacion": "Notificacion 1",
  "usuarioId":1,
  "correo": "Correo@gmail.com"
}

### NOTIFICACION SMS PUERTO NOTIFICATION
POST http://localhost:8150/v1/api/notification/sms
Content-Type: application/json

{
  "notificacion": "Notificacion 1",
  "usuarioId":1,
  "telefono": "+519 78789484"
}

### NOTIFICACION CORREO PUERTO GATEWAY

POST http://localhost:8283/ms-notification/v1/api/notification/correo
Content-Type: application/json

{
  "notificacion": "Notificacion 1",
  "usuarioId":1,
  "correo": "Correo@gmail.com"
}

### NOTIFICACION SMS PUERTO GATEWAY
POST http://localhost:8283/ms-notification/v1/api/notification/sms
Content-Type: application/json

{
  "notificacion": "Notificacion 1",
  "usuarioId":1,
  "telefono": "+519 78789484"
}

###

