spring:
  application:
    name: ms-discovery
server:
  port: ${PORT:8761}
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  server:
    enable-self-preservation: false
   # eviction-interval-timer-in-ms: 500
    #response-cache-update-interval-ms: 500 #default 30000
    use-read-only-response-cache: false

endpoints:
  shutdown:
    enabled: true
    sensitive: false